"""Whisper sidecar configuration loader.

Owner-only Mac mini service. Env-driven via pydantic-settings; reads
``~/.config/whisper-server/.env`` (mode 600) generated by
``setup-mac-sidecar.sh``. The bearer token MUST be at least 32 chars
or the service refuses to boot.
"""

from __future__ import annotations

import os
from pathlib import Path

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _user_env_file() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME")
    root = Path(base) if base else Path.home() / ".config"
    return root / "whisper-server" / ".env"


class WhisperSettings(BaseSettings):
    """Whisper sidecar settings.

    Env precedence: process env > user config file (``.env``) > defaults.
    """

    model_config = SettingsConfigDict(
        env_file=[_user_env_file(), Path(".env")],
        extra="ignore",
    )

    # Authorization. The token is generated by setup-mac-sidecar.sh as
    # ``secrets.token_urlsafe(32)`` (minimum 43 chars after URL encoding).
    whisper_api_token: str = Field(min_length=32)

    # Bind address. Default 127.0.0.1 — the SSH reverse tunnel from the
    # Mac mini to the VPS does the cross-host transport, so the FastAPI
    # process only needs to accept connections from the local SSH
    # client. Binding to loopback closes off any LAN-side exposure
    # (e.g. another device on the owner's home network).
    host: str = "127.0.0.1"
    port: int = 9000

    # Model. Pinned to the canonical mlx-community repo; override via
    # env if Apple flips the canonical repo.
    model_repo: str = "mlx-community/whisper-large-v3-turbo"
    default_language: str = "ru"

    # Caps. Server-side enforcement is belt-and-suspenders; bot side
    # also caps these.
    max_audio_bytes: int = 100 * 1024 * 1024
    max_duration_sec: int = 3 * 3600
    yt_dlp_max_filesize_mb: int = 500
    yt_dlp_timeout_sec: int = 600
    yt_dlp_min_disk_free_bytes: int = 2 * 1024 * 1024 * 1024

    # Logging
    log_level: str = "INFO"

    @field_validator("whisper_api_token")
    @classmethod
    def _validate_token(cls, v: str) -> str:
        if len(v) < 32:
            raise ValueError(
                "WHISPER_API_TOKEN must be at least 32 chars; "
                "regenerate via `python -c 'import secrets; "
                "print(secrets.token_urlsafe(32))'`"
            )
        return v
