#!/usr/bin/env bash
# Phase 6c: Mac mini Whisper sidecar bootstrap.
#
# Idempotent — re-running on a fully-installed host updates pip deps and
# refreshes launchd plists, but does NOT regenerate the bearer token.
#
# Pre-requisites checked:
#   - Apple Silicon (arm64).
#   - Homebrew installed (auto-installed if missing).
#   - macOS 13.5+ (mlx requires Metal 3).
#
# Output:
#   - Bearer token printed once (post-generation) for owner to copy
#     into the VPS .env. Subsequent runs do not re-print it.
#   - MagicDNS hostname printed for owner to set as WHISPER_API_URL.
set -euo pipefail

# ---------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------
ARCH="$(uname -m)"
if [ "$ARCH" != "arm64" ]; then
    echo "ERROR: Apple Silicon required (uname -m == $ARCH, expected arm64)"
    exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew (interactive)..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# ffmpeg for audio decoding/normalisation; python@3.12 for mlx-whisper
# compat (3.13 has transitive lag per research RQ1).
brew install ffmpeg python@3.12 || true

# Tailscale CLI cask. The Mac App Store version sandboxes the CLI out
# of reach; brew cask is required for `tailscale up --advertise-tags`.
if ! command -v tailscale >/dev/null 2>&1; then
    brew install --cask tailscale-app || true
fi

# ---------------------------------------------------------------------
# Layout: ~/whisper-server/{.venv, logs/}
# ---------------------------------------------------------------------
SERVER_DIR="$HOME/whisper-server"
mkdir -p "$SERVER_DIR" "$SERVER_DIR/logs"

# Bring repo files into place. setup-mac-sidecar.sh is invoked from
# a checkout (via curl + bash, or `cd whisper-server && ./setup...`);
# we copy the runtime files into the installed location.
#
# F17 (fix-pack): the source already ships the ``whisper_server/``
# Python package so dev = prod. Copy the whole package as-is rather
# than reconstructing it from flat files — this keeps the repo layout
# importable for local ``uvicorn whisper_server.main:app`` runs.
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
rm -rf "$SERVER_DIR/whisper_server"
cp -R "$SOURCE_DIR/whisper_server" "$SERVER_DIR/whisper_server"
cp "$SOURCE_DIR/requirements.txt" "$SERVER_DIR/requirements.txt"

# venv (pin Python 3.12)
PYTHON_BIN="$(brew --prefix python@3.12)/bin/python3.12"
if [ ! -x "$SERVER_DIR/.venv/bin/python" ]; then
    "$PYTHON_BIN" -m venv "$SERVER_DIR/.venv"
fi
# shellcheck disable=SC1091
source "$SERVER_DIR/.venv/bin/activate"
pip install --upgrade pip
pip install -r "$SERVER_DIR/requirements.txt"

# ---------------------------------------------------------------------
# Bearer token
# ---------------------------------------------------------------------
mkdir -p "$HOME/.config/whisper-server"
chmod 700 "$HOME/.config/whisper-server"
TOKEN_FILE="$HOME/.config/whisper-server/.env"
if [ ! -f "$TOKEN_FILE" ] || ! grep -q "^WHISPER_API_TOKEN=" "$TOKEN_FILE"; then
    NEW_TOKEN="$("$SERVER_DIR/.venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')"
    {
        echo "# Generated by setup-mac-sidecar.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "WHISPER_API_TOKEN=$NEW_TOKEN"
    } >"$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
    echo
    echo "================================================================"
    echo " Generated WHISPER_API_TOKEN. Copy this line into your VPS"
    echo " ~/.config/0xone-assistant/secrets.env file:"
    echo
    grep "^WHISPER_API_TOKEN=" "$TOKEN_FILE"
    echo "================================================================"
    echo
fi

# ---------------------------------------------------------------------
# Tailscale auth
# ---------------------------------------------------------------------
if ! tailscale status >/dev/null 2>&1; then
    echo "Starting Tailscale auth (interactive browser flow)..."
    sudo tailscale up --advertise-tags=tag:whisper-mac --ssh
fi
TS_HOSTNAME="$(tailscale status --json | "$SERVER_DIR/.venv/bin/python" -c "import sys, json; print(json.load(sys.stdin)['Self']['DNSName'].rstrip('.'))" || true)"
if [ -n "$TS_HOSTNAME" ]; then
    echo
    echo "================================================================"
    echo " Tailscale MagicDNS hostname: $TS_HOSTNAME"
    echo " On the VPS, set in ~/.config/0xone-assistant/.env:"
    echo "     WHISPER_API_URL=http://$TS_HOSTNAME:9000"
    echo "================================================================"
    echo
fi

# ---------------------------------------------------------------------
# launchd plists (substitute __HOME__ at install time)
# ---------------------------------------------------------------------
LAUNCHD_DIR="$HOME/Library/LaunchAgents"
mkdir -p "$LAUNCHD_DIR"
for plist_name in "com.zeroxone.whisper-server.plist" "com.zeroxone.yt-dlp-update.plist"; do
    src="$SOURCE_DIR/$plist_name"
    dst="$LAUNCHD_DIR/$plist_name"
    sed "s|__HOME__|$HOME|g" "$src" >"$dst"
    label="${plist_name%.plist}"
    # Re-load: bootout (idempotent on missing) then bootstrap.
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$dst"
    echo "Loaded launchd job: $label"
done

# ---------------------------------------------------------------------
# Pre-download model (first-time only; ~1.6 GB).
# ---------------------------------------------------------------------
echo "Pre-warming mlx-whisper model (download ~1.6 GB if first run)..."
"$SERVER_DIR/.venv/bin/python" - <<'PYEOF' || echo "WARNING: model prewarm failed; first request will incur download latency."
import sys
try:
    import mlx_whisper
    import numpy as np
    silence = np.zeros(8000, dtype=np.float32)
    mlx_whisper.transcribe(
        silence,
        path_or_hf_repo="mlx-community/whisper-large-v3-turbo",
        language="ru",
    )
    print("model prewarmed ok")
except Exception as exc:
    print(f"prewarm failed: {exc}")
    sys.exit(1)
PYEOF

echo
echo "Setup complete. The sidecar is now running on http://$TS_HOSTNAME:9000"
echo "Test it with: curl http://$TS_HOSTNAME:9000/health"
