#!/usr/bin/env bash
# Phase 6c: Mac mini Whisper sidecar bootstrap.
#
# Idempotent — re-running on a fully-installed host updates pip deps and
# refreshes launchd plists, but does NOT regenerate the bearer token or
# the SSH tunnel key.
#
# Pre-requisites checked:
#   - Apple Silicon (arm64).
#   - Homebrew installed (auto-installed if missing).
#   - macOS 13.5+ (mlx requires Metal 3).
#
# Transport: SSH reverse tunnel (autossh -N -R 9000:localhost:9000) from
# the Mac to the VPS. The bot container on the VPS reaches the Mac via
# host.docker.internal:9000 (compose extra_hosts: host-gateway).
# Replaces the previous Tailscale design — Tailscale's default-route
# capture conflicts with the owner's AmneziaVPN.
#
# Output (printed once each on first run):
#   - WHISPER_API_TOKEN  — paste into VPS ~/.config/0xone-assistant/secrets.env.
#   - SSH public key     — paste into VPS ~/.ssh/authorized_keys with the
#                          port-forward restriction shown.
set -euo pipefail

# ---------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------
ARCH="$(uname -m)"
if [ "$ARCH" != "arm64" ]; then
    echo "ERROR: Apple Silicon required (uname -m == $ARCH, expected arm64)"
    exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew (interactive)..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# ffmpeg for audio decoding/normalisation; python@3.12 for mlx-whisper
# compat (3.13 has transitive lag per research RQ1); autossh keeps the
# reverse tunnel alive across NAT timeouts and Mac-side network blips.
brew install ffmpeg python@3.12 autossh || true

# ---------------------------------------------------------------------
# Layout: ~/whisper-server/{.venv, logs/}
# ---------------------------------------------------------------------
SERVER_DIR="$HOME/whisper-server"
mkdir -p "$SERVER_DIR" "$SERVER_DIR/logs"

# Bring repo files into place. setup-mac-sidecar.sh is invoked from
# a checkout (via curl + bash, or `cd whisper-server && ./setup...`);
# we copy the runtime files into the installed location.
#
# F17 (fix-pack): the source already ships the ``whisper_server/``
# Python package so dev = prod. Copy the whole package as-is rather
# than reconstructing it from flat files — this keeps the repo layout
# importable for local ``uvicorn whisper_server.main:app`` runs.
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
rm -rf "$SERVER_DIR/whisper_server"
cp -R "$SOURCE_DIR/whisper_server" "$SERVER_DIR/whisper_server"
cp "$SOURCE_DIR/requirements.txt" "$SERVER_DIR/requirements.txt"

# venv (pin Python 3.12)
PYTHON_BIN="$(brew --prefix python@3.12)/bin/python3.12"
if [ ! -x "$SERVER_DIR/.venv/bin/python" ]; then
    "$PYTHON_BIN" -m venv "$SERVER_DIR/.venv"
fi
# shellcheck disable=SC1091
source "$SERVER_DIR/.venv/bin/activate"
pip install --upgrade pip
pip install -r "$SERVER_DIR/requirements.txt"

# ---------------------------------------------------------------------
# Bearer token
# ---------------------------------------------------------------------
mkdir -p "$HOME/.config/whisper-server"
chmod 700 "$HOME/.config/whisper-server"
TOKEN_FILE="$HOME/.config/whisper-server/.env"
if [ ! -f "$TOKEN_FILE" ] || ! grep -q "^WHISPER_API_TOKEN=" "$TOKEN_FILE"; then
    NEW_TOKEN="$("$SERVER_DIR/.venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')"
    {
        echo "# Generated by setup-mac-sidecar.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "WHISPER_API_TOKEN=$NEW_TOKEN"
    } >"$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
    echo
    echo "================================================================"
    echo " Generated WHISPER_API_TOKEN. Copy this line into your VPS"
    echo " ~/.config/0xone-assistant/secrets.env file:"
    echo
    grep "^WHISPER_API_TOKEN=" "$TOKEN_FILE"
    echo "================================================================"
    echo
fi

# ---------------------------------------------------------------------
# SSH tunnel key
# ---------------------------------------------------------------------
# Dedicated key for the reverse tunnel. Kept out of the user's normal
# ~/.ssh/id_* so it can be revoked / rotated independently. Public key
# is added to VPS authorized_keys with `restrict,permitlisten="9000"`
# so it's good for nothing else (no shell, no other forwards).
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"
SSH_KEY_FILE="$HOME/.ssh/whisper_tunnel"
if [ ! -f "$SSH_KEY_FILE" ]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY_FILE" -N "" \
        -C "whisper-tunnel-mac-mini"
    chmod 600 "$SSH_KEY_FILE"
fi
SSH_PUB="$(cat "${SSH_KEY_FILE}.pub")"
echo
echo "================================================================"
echo " SSH tunnel public key — add to VPS authorized_keys with"
echo " port-forward restriction. From your laptop:"
echo
echo "   ssh 0xone@193.233.87.118 'cat >> ~/.ssh/authorized_keys' <<EOF"
echo "   restrict,permitlisten=\"9000\",permitopen=\"\" $SSH_PUB"
echo "   EOF"
echo
echo " Then on VPS enable GatewayPorts:"
echo "   sudo sed -i 's/^#GatewayPorts no/GatewayPorts yes/' /etc/ssh/sshd_config"
echo "   sudo systemctl reload sshd"
echo "================================================================"
echo

# ---------------------------------------------------------------------
# launchd plists (substitute __HOME__ at install time)
# ---------------------------------------------------------------------
LAUNCHD_DIR="$HOME/Library/LaunchAgents"
mkdir -p "$LAUNCHD_DIR"
for plist_name in \
    "com.zeroxone.whisper-server.plist" \
    "com.zeroxone.whisper-tunnel.plist" \
    "com.zeroxone.yt-dlp-update.plist"
do
    src="$SOURCE_DIR/$plist_name"
    dst="$LAUNCHD_DIR/$plist_name"
    sed "s|__HOME__|$HOME|g" "$src" >"$dst"
    label="${plist_name%.plist}"
    # Re-load: bootout (idempotent on missing) then bootstrap.
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$dst"
    echo "Loaded launchd job: $label"
done

# ---------------------------------------------------------------------
# Pre-download model (first-time only; ~1.6 GB).
# ---------------------------------------------------------------------
echo "Pre-warming mlx-whisper model (download ~1.6 GB if first run)..."
"$SERVER_DIR/.venv/bin/python" - <<'PYEOF' || echo "WARNING: model prewarm failed; first request will incur download latency."
import sys
try:
    import mlx_whisper
    import numpy as np
    silence = np.zeros(8000, dtype=np.float32)
    mlx_whisper.transcribe(
        silence,
        path_or_hf_repo="mlx-community/whisper-large-v3-turbo",
        language="ru",
    )
    print("model prewarmed ok")
except Exception as exc:
    print(f"prewarm failed: {exc}")
    sys.exit(1)
PYEOF

echo
echo "Setup complete. Sidecar listens on 127.0.0.1:9000 (loopback only)."
echo "Once you finish the VPS bootstrap (authorized_keys + GatewayPorts),"
echo "the bot container reaches it via http://host.docker.internal:9000."
echo
echo "Sanity check from this Mac:"
echo "  curl http://127.0.0.1:9000/health"
echo
echo "From the VPS once the tunnel is up:"
echo "  ssh 0xone@193.233.87.118 'curl -s http://172.17.0.1:9000/health'"
