"""First-run bootstrap for the vault directory (Q9 / R-8).

Invoked by :mod:`tools.gh.main._cmd_vault_commit_push` when
:func:`tools.gh._lib.git_ops.is_inside_work_tree` reports False on
``vault_dir``. Creates a standalone git repo with:

1. ``git init -b <branch>`` — explicit branch (``main`` per R-8) so we
   don't inherit the host's ``init.defaultBranch`` setting.
2. A pre-seeded ``.gitignore`` (SF-D7) excluding ``.tmp/`` + ``*.tmp``
   so the memory indexer's scratch files never ship to the backup
   remote. Written BEFORE the first commit so the exclude is effective
   immediately, not "from the next commit onward".
3. ``git remote add <remote_name> <remote_url>`` — the configured
   backup endpoint.
4. An empty bootstrap commit created via inline
   ``-c user.email=X -c user.name=Y`` (I-8.4: never touches the
   host's global ``.gitconfig``).

The helper intentionally does NOT push — the caller stages real
content and pushes the combined bootstrap + real commit in a single
subsequent ``git push`` so the remote never sees a "bootstrap only"
state that would then require a force push to supersede.
"""

from __future__ import annotations

from pathlib import Path

from tools.gh._lib.git_ops import _run_git

_GITIGNORE_TEMPLATE = (
    "# Auto-generated by vault_git_init bootstrap (phase 8, SF-D7).\n"
    "# Excludes transient paths that the memory indexer writes under\n"
    "# `<vault>/.tmp/` during re-index runs. These files are local\n"
    "# scratch and MUST NOT be shipped to the backup remote.\n"
    ".tmp/\n"
    "*.tmp\n"
)


def bootstrap(
    vault_dir: Path,
    *,
    remote_name: str,
    remote_url: str,
    branch: str,
    author_email: str,
    author_name: str = "vaultbot",
) -> None:
    """Initialise ``vault_dir`` as a standalone git repo with the remote + seed commit.

    Preconditions: caller has already ``mkdir``'d ``vault_dir`` (step 2 of
    the execution flow, B-A3). This function does NOT create the
    directory — it assumes it exists and is empty-or-content-only (no
    ``.git`` inside yet).

    Side effects:

    - Creates ``<vault_dir>/.git/``.
    - Creates ``<vault_dir>/.gitignore`` IF NOT already present. If an
      owner pre-populated a ``.gitignore`` (e.g. during a manual
      migration), we respect it verbatim and do not merge our template.
    - Adds a remote entry in ``.git/config``.
    - Creates exactly one empty bootstrap commit on ``branch``.

    Raises :class:`RuntimeError` on any ``git`` failure (via ``check=True``
    in :func:`_run_git`). Callers wrap with a JSON error handler at the
    CLI layer.
    """
    # Step 1: init the repo on the configured branch. `-q` suppresses
    # the default "Initialized empty Git repository" chatter so our JSON
    # output stays clean.
    _run_git(["init", "-q", "-b", branch], vault_dir, check=True)

    # Step 2: seed `.gitignore` BEFORE the first commit. If the file
    # already exists (e.g. the owner pre-populated it), we don't
    # overwrite — respecting pre-existing content is safer than merging.
    gitignore = vault_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE_TEMPLATE, encoding="utf-8")

    # Step 3: register the backup remote. Idempotency note — we rely on
    # the caller (`is_inside_work_tree` returned False) to guarantee
    # this is a fresh repo, so `remote add` will not clash with an
    # existing entry. If future callers relax that assumption they
    # should switch to `git remote set-url --add` or similar.
    _run_git(
        ["remote", "add", remote_name, remote_url],
        vault_dir,
        check=True,
    )

    # Step 4: stage the `.gitignore` + make the bootstrap commit. We use
    # `--allow-empty` so the sequence works even if an owner's
    # pre-existing `.gitignore` exactly matches our template (nothing
    # actually changed). The commit's date is whatever git picks from
    # the host clock — we don't need deterministic timestamps because
    # no consumer of this commit cares.
    _run_git(["add", ".gitignore"], vault_dir, check=True)
    _run_git(
        [
            "-c", f"user.email={author_email}",
            "-c", f"user.name={author_name}",
            "commit", "--allow-empty", "-q", "-m", "bootstrap",
        ],
        vault_dir,
        check=True,
    )


__all__ = ["bootstrap"]
