"""First-run bootstrap for the vault directory (Q9 / R-8).

Invoked by :mod:`tools.gh.main._cmd_vault_commit_push` when
:func:`tools.gh._lib.git_ops.is_inside_work_tree` reports False on
``vault_dir``. Creates a standalone git repo with:

1. ``git init -b <branch>`` — explicit branch (``main`` per R-8) so we
   don't inherit the host's ``init.defaultBranch`` setting.
2. ``git config core.hooksPath /dev/null`` (T4.1). Any future
   ``git commit`` / ``git push`` inside ``vault_dir`` must not execute
   repo-local hook scripts. This is defence in depth against a
   tampered backup that a restore operation might deposit at
   ``.git/hooks/*`` — even if an attacker plants a malicious
   ``post-checkout`` inside a restored repo, git will not find any
   hook at ``/dev/null`` and skip execution cleanly.
3. A pre-seeded ``.gitignore`` (SF-D7) excluding ``.tmp/`` + ``*.tmp``
   plus common sensitive-file patterns (``.env``, ``*.key``, ``.ssh/``
   etc) so the memory indexer's scratch files and any accidentally-
   dropped credentials never ship to the backup remote. Written BEFORE
   the first commit so the excludes are effective immediately, not
   "from the next commit onward". Merge semantics (T4.3): if the owner
   pre-populated ``.gitignore`` (manual migration), we preserve the
   curated content verbatim but append the two mandatory SF-D7 lines
   if they are missing — so migrating an existing vault into the
   backup flow is never an accidental data leak.
4. ``git remote add <remote_name> <remote_url>`` — the configured
   backup endpoint.
5. An empty bootstrap commit created via inline
   ``-c user.email=X -c user.name=Y`` (I-8.4: never touches the
   host's global ``.gitconfig``).

The helper intentionally does NOT push — the caller stages real
content and pushes the combined bootstrap + real commit in a single
subsequent ``git push`` so the remote never sees a "bootstrap only"
state that would then require a force push to supersede.
"""

from __future__ import annotations

from pathlib import Path

from tools.gh._lib.git_ops import _run_git

# Full template written when no .gitignore is present. Mirrors the
# sensitive-path denylists from `src/assistant/bridge/hooks.py` so the
# vault is never a back-door for credentials that the main file-path
# hook would block inside the project tree.
_GITIGNORE_TEMPLATE = (
    "# Auto-generated by vault_git_init bootstrap (phase 8, SF-D7 + T4.3).\n"
    "# Excludes transient paths that the memory indexer writes under\n"
    "# `<vault>/.tmp/` during re-index runs. These files are local\n"
    "# scratch and MUST NOT be shipped to the backup remote.\n"
    "/.tmp/\n"
    "*.tmp\n"
    "\n"
    "# Credential / secret patterns. Belt-and-suspenders — the owner\n"
    "# should not be storing these in the vault, but if they land here\n"
    "# accidentally (copy-paste, tool output, etc.) we must not push\n"
    "# them to the backup remote in plaintext.\n"
    ".env\n"
    ".env.*\n"
    ".ssh/\n"
    ".aws/\n"
    ".gnupg/\n"
    ".kube/\n"
    "id_rsa*\n"
    "id_ed25519*\n"
    "id_ecdsa*\n"
    "*.pem\n"
    "*.key\n"
    "credentials*\n"
)

# The two lines that MUST be present under every .gitignore the vault
# ever writes (SF-D7 invariant). If the owner pre-populates a
# `.gitignore`, these are appended when missing rather than replacing
# the curated content.
_MANDATORY_GITIGNORE_LINES: tuple[str, ...] = ("/.tmp/", "*.tmp")


def _ensure_gitignore(vault_dir: Path) -> None:
    """Create or merge ``.gitignore`` so SF-D7 invariants always hold.

    Semantics:

    - Fresh vault (no ``.gitignore``): write the full
      :data:`_GITIGNORE_TEMPLATE`.
    - Existing ``.gitignore``: preserve it verbatim; append any of
      :data:`_MANDATORY_GITIGNORE_LINES` that are missing. The appended
      block is guarded by a marker comment so repeat invocations are
      idempotent (they re-check presence before appending again).

    Line equality is normalised by stripping whitespace; ``"/.tmp/\\n"``
    and ``"/.tmp/"`` count as the same entry.
    """
    gitignore = vault_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE_TEMPLATE, encoding="utf-8")
        return

    existing_lines = gitignore.read_text(encoding="utf-8").splitlines()
    existing_stripped = {line.strip() for line in existing_lines}
    to_append = [
        line
        for line in _MANDATORY_GITIGNORE_LINES
        if line not in existing_stripped
    ]
    if not to_append:
        return

    with gitignore.open("a", encoding="utf-8") as f:
        # Leading blank line so the marker is visible in diffs and
        # doesn't glue to whatever the owner's last line was.
        f.write("\n# phase 8 auto-appended SF-D7 guards\n")
        for line in to_append:
            f.write(line + "\n")


def bootstrap(
    vault_dir: Path,
    *,
    remote_name: str,
    remote_url: str,
    branch: str,
    author_email: str,
    author_name: str = "vaultbot",
) -> None:
    """Initialise ``vault_dir`` as a standalone git repo with the remote + seed commit.

    Preconditions: caller has already ``mkdir``'d ``vault_dir`` (step 2 of
    the execution flow, B-A3). This function does NOT create the
    directory — it assumes it exists and is empty-or-content-only (no
    ``.git`` inside yet).

    Side effects:

    - Creates ``<vault_dir>/.git/``.
    - Sets ``core.hooksPath=/dev/null`` inside the repo (T4.1) so
      restored / tampered hooks cannot execute.
    - Creates ``<vault_dir>/.gitignore`` IF NOT already present. If an
      owner pre-populated a ``.gitignore`` (e.g. during a manual
      migration), we preserve their curated content verbatim but
      append the two mandatory SF-D7 lines (``/.tmp/`` + ``*.tmp``)
      when missing — T4.3 merge semantics.
    - Adds a remote entry in ``.git/config``.
    - Creates exactly one empty bootstrap commit on ``branch``.

    Raises :class:`RuntimeError` on any ``git`` failure (via ``check=True``
    in :func:`_run_git`). Callers wrap with a JSON error handler at the
    CLI layer.
    """
    # Step 1: init the repo on the configured branch. `-q` suppresses
    # the default "Initialized empty Git repository" chatter so our JSON
    # output stays clean.
    _run_git(["init", "-q", "-b", branch], vault_dir, check=True)

    # Step 2 (T4.1): neutralise `.git/hooks/*`. Setting `core.hooksPath`
    # to `/dev/null` makes git search for hooks under that path instead
    # of the default `<repo>/.git/hooks/` — and since `/dev/null` is
    # never a directory containing executables, no hook ever runs. This
    # is a belt-and-suspenders against a tampered restore that might
    # plant a malicious `post-checkout` / `post-commit` script.
    _run_git(
        ["config", "core.hooksPath", "/dev/null"], vault_dir, check=True
    )

    # Step 3: seed / merge `.gitignore` BEFORE the first commit. T4.3
    # merge semantics: preserve any owner-curated content but guarantee
    # the two mandatory SF-D7 lines are present, even when migrating an
    # existing vault into the backup flow.
    _ensure_gitignore(vault_dir)

    # Step 4: register the backup remote. Idempotency note — we rely on
    # the caller (`is_inside_work_tree` returned False) to guarantee
    # this is a fresh repo, so `remote add` will not clash with an
    # existing entry. If future callers relax that assumption they
    # should switch to `git remote set-url --add` or similar.
    _run_git(
        ["remote", "add", remote_name, remote_url],
        vault_dir,
        check=True,
    )

    # Step 5: stage the `.gitignore` + make the bootstrap commit. We use
    # `--allow-empty` so the sequence works even if an owner's
    # pre-existing `.gitignore` exactly matches our template (nothing
    # actually changed). The commit's date is whatever git picks from
    # the host clock — we don't need deterministic timestamps because
    # no consumer of this commit cares.
    _run_git(["add", ".gitignore"], vault_dir, check=True)
    _run_git(
        [
            "-c", f"user.email={author_email}",
            "-c", f"user.name={author_name}",
            "commit", "--allow-empty", "-q", "-m", "bootstrap",
        ],
        vault_dir,
        check=True,
    )


__all__ = ["bootstrap"]
